[project]
name = "mint-eip"
authors = ["Mint EIP Team"]
description = "Decentralized identity verification and reputation system"
telemetry = false
requirements = []
[contracts.eip-identity]
path = "contracts/eip-identity.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
